# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GattoPuccino < Formula
  desc "GattoPuccino is a command-line tool that takes an image file and applies a coffee-themed color palette to it. It supports four different flavors - latte, frappe, macchiato, and mocha. GattoPuccino uses the ImageMagick cli tool to apply the color palette."
  homepage "https://github.com/DevMentat/GattoPuccino/"
  version "1.5"

  depends_on "imagemagick"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v1.5/GattoPuccino_1.5_darwin_arm64.tar.gz"
      sha256 "d2979d30fb5b6e01bb05345d5e439dab78a8f10f2aaa877747bdd54df5450d7c"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DevMentat/GattoPuccino/releases/download/v1.5/GattoPuccino_1.5_linux_arm64.tar.gz"
      sha256 "57fcb18023b2eda92b452d4d3c690c434c81a2d19126a8d1159e010fa2cd4aa4"

      def install
        bin.install "GattoPuccino"
      end
    end
  end

  def caveats
    <<~EOS
      gattopuccino <flavor> <image> (Flavor available: latte, frappe, macchiato, or mocha)
    EOS
  end
end
