name: CICD
# Pipeline conditions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  # Build Workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.2'

      - name: Install dependencies
        run: |
          go version

      - name: Run build
        run: go build .

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}