name: CICD
# Pipeline conditions

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  # Build Workflow
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        
      - run: git fetch --force --tags
      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}